"""Foreign-key update & delete policies.

Tables themselves are defined as Django models (`core/models.py`) and created
with `makemigrations` / `migrate`. This module owns ONLY the foreign-key
update/delete strategies, for two reasons:

  * The project bypasses the ORM for all queries (see `core/db.py`), so Django's
    `on_delete` — which the ORM enforces in Python, not in the database — never
    runs for our raw-SQL writes. The behaviour must be enforced at the DB level.
  * Django models cannot express `ON UPDATE` referential actions at all.

So after migrations create the tables and their default foreign keys, this
module replaces each foreign key with one that declares explicit ON UPDATE /
ON DELETE behaviour. Apply it (after every `migrate`) with:

    python manage.py apply_constraints

Statements are idempotent (drop-if-exists, then add) so they can be re-applied
safely. The identifiers below are trusted constants, not user input — building
DDL by formatting is fine here; the "no string-formatted SQL" rule is about
query parameters in `core/db.py`.
"""

SQL_CONSTRAINTS = [
    """ALTER TABLE employee DROP CONSTRAINT IF EXISTS chk_emp_age;""",
    """
    ALTER TABLE employee
    ADD CONSTRAINT chk_emp_age
    CHECK (date_of_birth <= CURRENT_DATE - INTERVAL '18 years');
    """,
    """ALTER TABLE employee DROP CONSTRAINT IF EXISTS chk_emp_phone;""",
    """
    ALTER TABLE employee
    ADD CONSTRAINT chk_emp_phone
    CHECK (phone_number LIKE '+%' AND LENGTH(phone_number) <= 13);
    """,
    """ALTER TABLE customer_card DROP CONSTRAINT IF EXISTS chk_card_phone;""",
    """
    ALTER TABLE customer_card
    ADD CONSTRAINT chk_card_phone
    CHECK (phone_number LIKE '+%' AND LENGTH(phone_number) <= 13);
    """,
    """ALTER TABLE employee DROP CONSTRAINT IF EXISTS chk_emp_salary;""",
    """ALTER TABLE employee ADD CONSTRAINT chk_emp_salary CHECK (salary >= 0);""",
    """ALTER TABLE store_product DROP CONSTRAINT IF EXISTS chk_sp_price;""",
    """ALTER TABLE store_product ADD CONSTRAINT chk_sp_price CHECK (selling_price >= 0);""",
    """ALTER TABLE store_product DROP CONSTRAINT IF EXISTS chk_sp_amount;""",
    """ALTER TABLE store_product ADD CONSTRAINT chk_sp_amount CHECK (products_number >= 0);""",
    """ALTER TABLE customer_card DROP CONSTRAINT IF EXISTS chk_card_percent;""",
    """ALTER TABLE customer_card ADD CONSTRAINT chk_card_percent CHECK (percent >= 0 AND percent <= 100);""",
    """ALTER TABLE "check" DROP CONSTRAINT IF EXISTS chk_chk_sum;""",
    """ALTER TABLE "check" ADD CONSTRAINT chk_chk_sum CHECK (sum_total >= 0);""",
    """ALTER TABLE "check" DROP CONSTRAINT IF EXISTS chk_chk_vat;""",
    """ALTER TABLE "check" ADD CONSTRAINT chk_chk_vat CHECK (vat >= 0);""",
    """ALTER TABLE sale DROP CONSTRAINT IF EXISTS chk_sale_price;""",
    """ALTER TABLE sale ADD CONSTRAINT chk_sale_price CHECK (selling_price >= 0);""",
    """ALTER TABLE sale DROP CONSTRAINT IF EXISTS chk_sale_amount;""",
    """ALTER TABLE sale ADD CONSTRAINT chk_sale_amount CHECK (product_number >= 0);""",
    """
    ALTER TABLE product
    ADD CONSTRAINT product_category_number_fk
    FOREIGN KEY (category_number) REFERENCES category(category_number)
    ON UPDATE CASCADE ON DELETE NO ACTION;
    """,
    """
    ALTER TABLE store_product
    ADD CONSTRAINT store_product_upc_prom_fk
    FOREIGN KEY ("UPC_prom") REFERENCES store_product("UPC")
    ON UPDATE CASCADE ON DELETE SET NULL;
    """,
    """
    ALTER TABLE store_product
    ADD CONSTRAINT store_product_id_product_fk
    FOREIGN KEY (id_product) REFERENCES product(id_product)
    ON UPDATE CASCADE ON DELETE NO ACTION;
    """,
    """
    ALTER TABLE "check"
    ADD CONSTRAINT check_id_employee_fk
    FOREIGN KEY (id_employee) REFERENCES employee(id_employee)
    ON UPDATE CASCADE ON DELETE NO ACTION;
    """,
    """
    ALTER TABLE "check"
    ADD CONSTRAINT check_card_number_fk
    FOREIGN KEY (card_number) REFERENCES customer_card(card_number)
    ON UPDATE CASCADE ON DELETE NO ACTION;
    """,
    """
    ALTER TABLE sale
    ADD CONSTRAINT sale_upc_fk
    FOREIGN KEY ("UPC") REFERENCES store_product("UPC")
    ON UPDATE CASCADE ON DELETE NO ACTION;
    """,
    """
    ALTER TABLE sale
    ADD CONSTRAINT sale_check_number_fk
    FOREIGN KEY (check_number) REFERENCES "check"(check_number)
    ON UPDATE CASCADE ON DELETE CASCADE;
    """,
    """ALTER TABLE store_product DROP CONSTRAINT IF EXISTS chk_sp_loop;""",
    """ALTER TABLE store_product ADD CONSTRAINT chk_sp_loop CHECK ("UPC" != "UPC_prom");""",
]


def drop_foreign_keys(cursor, table, column):
    """
    Find and delete all existing foreign keys for a specific column,
    regardless of the name generated by Django.
    """
    cursor.execute(
        """
                   SELECT tc.constraint_name
                   FROM information_schema.table_constraints AS tc
                            JOIN information_schema.key_column_usage AS kcu
                                 ON tc.constraint_name = kcu.constraint_name
                                     AND tc.table_schema = kcu.table_schema
                   WHERE tc.constraint_type = 'FOREIGN KEY'
                     AND tc.table_name = %s
                     AND LOWER(kcu.column_name) = LOWER(%s);
                   """,
        [table, column],
    )

    constraints = cursor.fetchall()
    for (constraint_name,) in constraints:
        cursor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT "{constraint_name}";')


def apply(cursor):
    """(Re)create each constraint with its explicit update/delete policy."""

    drop_foreign_keys(cursor, "product", "category_number")

    drop_foreign_keys(cursor, "store_product", "UPC_prom")
    drop_foreign_keys(cursor, "store_product", "id_product")

    drop_foreign_keys(cursor, "check", "id_employee")
    drop_foreign_keys(cursor, "check", "card_number")

    drop_foreign_keys(cursor, "sale", "UPC")
    drop_foreign_keys(cursor, "sale", "check_number")

    for sql in SQL_CONSTRAINTS:
        cursor.execute(sql)
