version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: zlagoda_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: zlagoda_db
    ports:
      - "5432:5432"
    restart: unless-stopped