# Generated by Django 5.2.15 on 2026-06-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("category_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="CustomerCard",
            fields=[
                (
                    "card_number",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("cust_surname", models.CharField(max_length=50)),
                ("cust_name", models.CharField(max_length=50)),
                (
                    "cust_patronymic",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("phone_number", models.CharField(max_length=13)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=9, null=True)),
                ("percent", models.IntegerField()),
            ],
            options={
                "db_table": "customer_card",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id_employee",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("empl_surname", models.CharField(max_length=50)),
                ("empl_name", models.CharField(max_length=50)),
                (
                    "empl_patronymic",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("empl_role", models.CharField(max_length=10)),
                ("salary", models.DecimalField(decimal_places=4, max_digits=13)),
                ("date_of_birth", models.DateField()),
                ("date_of_start", models.DateField()),
                ("phone_number", models.CharField(max_length=13)),
                ("city", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=9)),
            ],
            options={
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "check_number",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("print_date", models.DateTimeField()),
                ("sum_total", models.DecimalField(decimal_places=4, max_digits=13)),
                ("vat", models.DecimalField(decimal_places=4, max_digits=13)),
                (
                    "card_number",
                    models.ForeignKey(
                        blank=True,
                        db_column="card_number",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.customercard",
                    ),
                ),
                (
                    "id_employee",
                    models.ForeignKey(
                        db_column="id_employee",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "check",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id_product", models.IntegerField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("characteristics", models.CharField(max_length=100)),
                (
                    "category_number",
                    models.ForeignKey(
                        db_column="category_number",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.category",
                    ),
                ),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "UPC",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("selling_price", models.DecimalField(decimal_places=4, max_digits=13)),
                ("products_number", models.IntegerField()),
                ("promotional_product", models.BooleanField()),
                (
                    "UPC_prom",
                    models.ForeignKey(
                        blank=True,
                        db_column="UPC_prom",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.storeproduct",
                    ),
                ),
                (
                    "id_product",
                    models.ForeignKey(
                        db_column="id_product",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.product",
                    ),
                ),
            ],
            options={
                "db_table": "store_product",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_number", models.IntegerField()),
                ("selling_price", models.DecimalField(decimal_places=4, max_digits=13)),
                (
                    "check_number",
                    models.ForeignKey(
                        db_column="check_number",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.check",
                    ),
                ),
                (
                    "UPC",
                    models.ForeignKey(
                        db_column="UPC",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.storeproduct",
                    ),
                ),
            ],
            options={
                "db_table": "sale",
                "unique_together": {("UPC", "check_number")},
            },
        ),
    ]
